PySimpleSQL/pysimplesql

- pysimplesql/pysimplesql.py
Hello!
I'm working on an internal program for my company and found your awesome pysimplesql. I have several changes I'll open pull-requests for over the next little bit.
This first one was to add 'set_Mline_size'. The ability to set a multi-line input record size globally was missing, so I added it.
> Add set_Mline_size

- pysimplesql/pysimplesql.py
Turns out I didn't catch all the issues last time.
Putting this up higher in your ifs.
The problem was, when there is no record, the element_val would still either be False (default pysimplegui), or it could even be 'True'.
> Fix for Checkboxes

- pysimplesql/pysimplesql.py
self.requery(update_elements)
update_elements = True
but requery's first arg is select_first. So this was calling first(), that then called update_elements on the entire form - deleting unsaved changes on other unrelated tables
> Small fix for save_records

- pysimplesql/pysimplesql.py
commit 16285a332ad823bb919f4ccc734bc25ad0f9a926
Author: ssweber <57631333+ssweber@users.noreply.github.com>
Date:   Wed Feb 8 15:42:04 2023 -0500
Add self.table to update_elements
Add self.table so that other unsaved changes arn't lost.
In all these examples,
```
if dependents: self.requery_dependents()
```
already calls requery -> first() -> update_elements(self.table) on the dependent.
commit 39825389db2112a41c261d3b7af17051b61a6df0
Author: ssweber <57631333+ssweber@users.noreply.github.com>
Date:   Wed Feb 8 14:03:59 2023 -0500
Prompt_save for insert / fix for requery
requery() calls first(), that then calls update_elements().
commit 9bb8022c7a06e963825026a892f757d4c9358b77
Author: ssweber <57631333+ssweber@users.noreply.github.com>
Date:   Wed Feb 8 14:15:23 2023 -0500
Fix for …
> Squashed commit of the following:

- pysimplesql/pysimplesql.py
I saw how you keep the current_index in-bounds under     @current_index.setter
This cleans that up a bit.
> Better fix for child-reparenting IndexError

- pysimplesql/pysimplesql.py
This merges all saving under save_records. Now all your message-logic (success,failed,etc) is used for prompt_save :)
save_record_recursive is called for every top-level (parentless) record, which then saves bottom to top.
Instead of calling update_elements() at end of Form.save_records and Form.prompt_save, we can let save_record handle updating.
> Merge Form and Query prompt save under save_records

- pysimplesql/pysimplesql.py
I'm not sure if this was intentional or not.
This was using the database default generator, instead of the parent.pk
eg
`Did not set default for id. Setting default for bike_repair_id to 1`
I think in general if inserting a child under an parent, we'd want to pass in the parent pk.
> Defaults is overwriting r.fk_column on insert

- pysimplesql/pysimplesql.py
My bad again! I had copied logic for editprotect when disabling nav buttons... and introduced a big slowdown.
Also fixed logic for first/previous.
> Fixing multiple calls to update_element_states

- pysimplesql/pysimplesql.py
Here was a really easy win 😄 I didn't see any changed behavior with this.
I timed 50 iterations of switching between two parent records on my parent/child/grandparent form:
```
frm['person'].set_by_pk(2)
frm['person'].set_by_pk(1)
```
Before - 43 seconds
After - 26 seconds.
> Use table_name if available on first for-loop of update_elements

- pysimplesql/pysimplesql.py
On one of the last commits, you deleted the if len(index) to catch when there isn't a pk_position set yet.
This rewrites that logic, making it more explicit what we were trying to try/except with a if len(values)...
> Fix for empty table widget

- pysimplesql/pysimplesql.py
max_pk was returning None when there were no rows. Don't know if you want to fix it here, or in max_pk... but looks like you were trying to catch it here with the `return n if n else 1`
> Fixes an unsupported operand type between Nonetype and Int when table is empty

- pysimplesql/pysimplesql.py
This fixed it from emitting `_TIMEOUT_` on each heading sort. Give it a try.
> Possible fix for _TIMEOUT_ on each Heading Sort

- pysimplesql/pysimplesql.py
I'll post a before and after video to demonstrate.
Essential, I'm in records_changed, I'm having it ignore simple formatting issues with checkboxes. New ones will still either be 'True','False', or 1/0. But why bug people if you don't have to.
> Fixes most checkbox styles

- pysimplesql/pysimplesql.py
I found when testing 'PRAGMA foreign_keys = ON' that current sqldriver was deleting records that only used foreign-key in drop-downs.. not as update_cascade
> Fix sqldriver to not delete NON update_cascade children

- pysimplesql/pysimplesql.py
Fixed this on the quick-editor awhile back. Otherwise on first event the whole window updates to the theme set by the user.
> Have progressbar use ttk_theme

- pysimplesql/pysimplesql.py
This was easier than I thought.
Here's how it works on my parent/child/grandchild/great-grandchild table:
```
INFO:pysimplesql.pysimplesql:Executing query: DELETE FROM person INNER JOIN service ON bike_repair.id = service.bike_repair_id INNER JOIN bike_repair ON bike.id = bike_repair.bike_id INNER JOIN bike ON person.id = bike.person_id WHERE person.id = 1  None
INFO:pysimplesql.pysimplesql:Executing query: DELETE FROM person INNER JOIN bike_repair ON bike.id = bike_repair.bike_id INNER JOIN bike ON person.id = bike.person_id WHERE person.id = 1  None
INFO:pysimplesql.pysimplesql:Executing query: DELETE FROM person INNER JOIN bike ON person.id = bike.person_id WHERE person.id = 1  None
INFO:pysimplesql.pysimplesql:Executing query: DELETE FROM person INNER JOIN car ON person.id = …
```
> Recursive delete implemented as “delete from table where pk_column in (…inner joins)

- pysimplesql/pysimplesql.py
I fixed a reversion, where child PK was being next_pk(), but child table may have many rows, which creates Unique Error on insert.
Also switched it to create a TEMPORARY TABLE as tmp_tablenamehere, to avoid an clashes.
> Cleaned up Duplicate

- pysimplesql/pysimplesql.py
I realized, that a table with lots of dependents will have a lag on parent change, waiting to update_elements(self.table). after all the dependents.
That's a remnant of that past, where dependents didn't do their own update_elements(self.table).
> Switch order of update_elements(self.table) and requery_dependents

- pysimplesql/language_pack.py
- pysimplesql/pysimplesql.py
#202
Giving this a little more prominence. It can always be overridden at the dataset level.
String-like default is used exclusively for the description column. We have the duplicate “Copy of”, so I see this as similar.
I'll be adding in your docker progress bars, and then will clean up our extra language-packs to match.
> Add 'New Record' to languagepack

- examples/MySQL_examples/docker/Docker_create.py
- examples/MySQL_examples/docker/Dockerfile
- examples/MySQL_examples/journal_mysql_docker.py
- pysimplesql/docker_utils.py
- pysimplesql/pysimplesql.py
Docker now working and providing a MySQL server for the example.  I have a little more work to do with the image to make the data persist and not start fresh each time, but I will work on that as a separate issue.
There was also a problem with the Mysql SQLDriver for getting table names and getting column info.  I'm not sure of the exact reason, but the HelioHost table_name field is lower case, and the Docker container MySQL server returned TABLE_NAME.  This could be because of different MySQL versions, or because of the change from the mysql-connector library to the mysql-connector-python library.
A similar issue was found with getting column info - the sql data type (domain) was being returned as a string from HelioHost, but as a bytes object from the Docker MySQL server.  Again, it …
> MySQL Docker now working

- pysimplesql/pysimplesql.py
Improves the progress bar by adding a threaded animate() method.  This bounces the bar back and forth indefinitely until .close() is called.  I wanted this because I'm working on a method to install Java in the background, and I haven't found a way to do it in a way that reports progress as it installs.  Of course, an indeterministic progress bar is helpful in many cases anyway.
from time import sleep
import pysimplesql as ss
pb = ss.ProgressBar("My Progressbar")
pb.animate()
sleep(15)
pb.close()
> Progress bar improvement

- pysimplesql/pysimplesql.py
This didn't format automatically like it normally does.  Fixed manually
> Fix Ruff run - lines too long

- pysimplesql/pysimplesql.py
Maybe you know where to fix this better?
Not-null that didn't have a default were showing up as 'None' in fields. I guess the row was returning 'None' instead of `None`.
> Return empty string for string-like null-default

- examples/MSAccess_examples/install_java.py
Just cycle between two phrases:
"Please wait while OpenJDK JRE is installed locally..."
"Still working... Thank you for your patience."
It also shows how flexible the config is - the entire thing does not need defined, just the config keys that you want to change
> Java installer phrase improvements

- pysimplesql/pysimplesql.py
I just ran into this today, working to setup a form using an [example Northwind database](https://github.com/jpwhite3/northwind-SQLite3) 
The example had 'Order Details' with a space. I think it was a mistake, but obviously pysimplesql didn't like that. 
- Is this so un-common, its not worth even caring about?
- If we should try to fix, should we quote by default? Single, double? 
- What about column_quote?
Do we hard-code it?
`super().__init__(name="SQLite", placeholder="?", table_quote=""")`
Or let the user pass a quote option when setting up the SqlDriver?
`ss.Driver.sqlite("./northwind.db", table_quote="'")`
> Adding quote_table for sqlite

- pysimplesql/pysimplesql.py
`with open` was using the local cp1252, rather than utf-8 on my lappy.
That created problems when executing the Northwind sql script with unicode names.
I think utf-8 be default makes sense. When you're not on a deadline, let me know if that makes sense to you.
> Add sql_script_encoding, default "utf-8", to pass to execute_script

- examples/MSAccess_examples/install_java.py
- pysimplesql/pysimplesql.py
Using my new write powers to work in the main pysimplesql repository! Now you can easily try out my changes before committing :)
This loads modules necessary for the sqldriver drivers on their init, with a popup if module is not found. So now a user doesn't need to install all database drivers, just to use sqlite. Then we can add all the [optionals to setup.py](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies) 
I tested this, and it works ok... but let me know if there is a more clean way without using global.
What are your thoughts on external requirements? Like the ODBC for sqlserver, or java jre for access?
> Import modules when init sqldriver driver

- pysimplesql/pysimplesql.py
@PySimpleSQL 
This strips down _SortCallbackWrapper, and moves it to sort, which is where I think it should be, so a user can call it programmatically.
Along with a few fixes.
> Moved things from _SortCallbackWrapper to sort

- pysimplesql/pysimplesql.py
If a save fails during a prompt-save, now we:
1) update_selectors() - do this for all selectors, because prompt-save might have been prompted by parent, while save_fail came from dependent. 
2) return SAVE_FAIL, which now will return in set_by_index/pk/first/prev/next/last
https://user-images.githubusercontent.com/57631333/235143763-e39387f3-27a4-4265-b707-8f9a3706fb90.mp4
> Fix prompt save dataloss

- pysimplesql/pysimplesql.py
For CellEdit, I needed to allow clicking same row again without triggering a prompt-save.
So I added
```
if self.current_index == idx:
return
````
However, if self.rows of a Dataset was already empty, self.current_index would already be at 0.
So instead, have insert_record do it's own index/update_elements/requery_dependents.
(Also deleted the current_index check in set_by_pk, since it now calls set_by_index anyway.)
> Fix insert_record in empty self.rows

- pysimplesql/pysimplesql.py
If the description_column has changed, or a new record inserted, we want to make sure to update other elements that may depend on it, that otherwise wouldn't be requeried because they are not setup as on_update_cascade.
**Updates**
- _get_description_for_pk so that it doesn't show unsaved changes to another table
**Relationship.get_dependent_columns**
Returns a dictionary of the `DataSet.key` and column names that use the description_column text of the given parent table in their `ElementRow` objects.
**DataSet.column_in_tableheading**:
Returns True if column is in tableheading of DataSet selector(s).
> Smarter updating after save

- examples/SQLite_examples/journal_internal.py
This was never changed when the examples were moved to separate folders
> fix path for Journal.db

- examples/SQLite_examples/orders.py
xpnative ttk theme only works on WIndows, as it uses the Window's API to generate the GUI elements.
This will allow for orders.py to work on other OS's (though not quite as pretty)
> Fix orders.py example for Linux

- pysimplesql/pysimplesql.py
PyPi version 4.60.~ doesn't have support for the 'quick_check', and I bungled handling it before.
> Fix for lazytable, PyPi PySimpleGUI version
