PySimpleSQL/pysimplesql

pysimplesql/pysimplesql.py

requery() calls first(), that then calls update_elements().

Prompt_save for insert / fix for requery

---

pysimplesql/pysimplesql.py

Reverts PySimpleSQL/pysimplesql#45
This did break some things on my end.  Reverting to try to figure out what's going on

Revert "Prompt_save for insert / fix for requery"

---

pysimplesql/pysimplesql.py

Reverts PySimpleSQL/pysimplesql#45
This did break some things on my end.  Reverting to try to figure out what's going on
You're right, we will move this into the development branch

Revert "Small fix for save_records"

---

pysimplesql/pysimplesql.py

Reverts PySimpleSQL/pysimplesql#47
Just reverting everything today.  We should redo this into the develpment branch.  I'll have to figure out what actually broke my large project... (it may have been before these 3, but want to roll back to see)

Revert "Fix for Checkboxes"

---

pysimplesql/pysimplesql.py

Does this look right?
Hits this when you delete all the records

Fix for get_min_pk at use in requery

---

pysimplesql/pysimplesql.py

Places where we are already getting the information, so use it again.

Little optimizations

---

examples/journal_with_data_manipulation.py
pysimplesql/pysimplesql.py

Here’s all of those pull requests as 1 total, if you’ll like to merge them all together

Squashed open pull requests.

---

examples/journal_with_data_manipulation.py
pysimplesql/pysimplesql.py

Here's a quick example of simple transform I cobbled together so you could test out.

Example of simple transform

---

pysimplesql/pysimplesql.py

I think we need prompt_save on Quick Editor...
Query1 - Make changes
Query2 - open Quert1 quick editor. Requery
Query1 - Changes lost
And autosave for Form/Query allows easy  persistent setting

Add autosave to quick_editor, add autosave parameter on Form and Query

---

pysimplesql/pysimplesql.py

I'm sure that was frustrating!
See: https://github.com/PySimpleGUI/PySimpleGUI/issues/1154
Guess you need to put it in a invisible column to keep it's spot.

Marker fix

---

pysimplesql/pysimplesql.py

Testing on my work project. Form.prompt_save wasn't resetting virtual rows.

Purge virtual if NO to form prompt_save

---

pysimplesql/pysimplesql.py

We fixed this in selectors... need it here too

Prevent partial Key match in self.callbacks

---

pysimplesql/pysimplesql.py

We get the self._simple_transform.items() from Query.

Missing self in transform call

---

pysimplesql/pysimplesql.py

Sorry, put the wrong thing here. Fixed now

where_column checkbox fix

---

pysimplesql/pysimplesql.py

Skip sql, just purge virtual and update elements / requery dependents

Delete for virtual rows, disable duplicate for virtual

---

pysimplesql/pysimplesql.py

These got overwritten. Repulling

Virtual delete disallow duplicate

---

pysimplesql/pysimplesql.py

Changed this to pass around update_elements=False instead of a Form-level lock.

Cleaning up skip_update_elements

---

pysimplesql/pysimplesql.py

Only needed 1 change.
I updated the update_event_states to be type(element) in to match.

Add sg.Text as available field element

---

pysimplesql/pysimplesql.py

I modeled after your selector/action logic. First set key, then run keygen on it.

Correct fix for field() key

---

examples/journal_internal.py

Way better. Thank you for your suggestion. Turns out we didn't even need a new function. You had it already 😄 
I think I just didn't realize needed to set initial state before main loop...

Edit protect example

---

pysimplesql/pysimplesql.py

Adds our own popups, so we can customize the button text, read changes based on key (instead of button text), and customize the quick_message

Langpack v2

---

pysimplesql/language_pack.py
pysimplesql/pysimplesql.py

'Can you look at this dict and make a version that is more professional and consistent?'
I had to add back the line-breaks. Maybe  next time I'll try 'Please keep \n unaltered.

ChatGPT cleaned up english

---

pysimplesql/language_pack.py
pysimplesql/pysimplesql.py

then we'll have to do ss.language_pack = ss.lp['yodo']
After this merges, will need to check to see if we need to add 'global lang' to popups and the quick-editor.

added german, french, spanish, monty-python version

---

pysimplesql/pysimplesql.py

I copy pasted your lost changes... incorrectly.
now it will match:

FIX FIX FIX ResultSet

---

pysimplesql/pysimplesql.py

I think this is what we agreed to, but let me know if I was mistaken.

Integrate size setters

---

pysimplesql/pysimplesql.py

Wanted to get this done before adding a delete_cascade version.

Convert to use relationship class methods

---

pysimplesql/pysimplesql.py

Fixed the merge conflict. Ready to go!

_SortCallbackWrapper class

---

pysimplesql/pysimplesql.py

Will need to check for mysql/postgres

Restore notnull constraints in sqlite

---

pysimplesql/pysimplesql.py

notnull defaults wasn't working. I mode the logic a little more explicit.
Also changed the default INT/INTEGER to 0, I think you'll want this to avoid pre-checking checkboxes, or filling in a value.

Fix for notnull defaults

---

pysimplesql/pysimplesql.py

I think this reads better.
Changed 
_update_cascade -> on_update_cascade
_delete_cascade -> on_delete_cascade

Remove leading underscore on cascade properties

---

pysimplesql/pysimplesql.py

Fix for set_fk_column_cascade

---

ruff.toml

add full-list of ruff rules, commented out by default

---

doc_examples/Column.1.py
doc_examples/ColumnInfo.1.py
doc_examples/ResultSet.1.py
pysimplesql/__init__.py
ruff.toml

get existing ruff rules working across all files
Now you can run:
`ruff check .`
in top-level directory.

Get current E/F ruff rules working across project

---

examples/PostgreSQL_examples/docker/Docker_create.py
pysimplesql/__init__.py
pysimplesql/docker_utils.py
pysimplesql/pysimplesql.py
ruff.toml
setup.py

- isort is another popular addon, that keeps imports sorted a repeatable way.
- And we didn't need all those global keygen/ global themepacks.

Ruff Isort and pylint warning

---

pysimplesql/pysimplesql.py

Slowly learning python :smile:
This gets rid of all the q/query +=

Clean up query creation

---

examples/MySQL_examples/journal_mysql_docker.py

Just doing this as a pull request as a test.  I do notice that I have a warning on screen stating that my mysql_docker branch does not exist on origin and will be created on orign.

Create a MySQL Docker example

---

pysimplesql/__init__.py

The short description comes from the 1st docstring in __init__.py.  Next release will update PyPi as well.
Long description comes from the readme.md

Update the PyPi short description

---

examples/MySQL_examples/docker/Docker_create.py
examples/MySQL_examples/docker/Dockerfile
examples/MySQL_examples/journal_mysql_docker.py
pysimplesql/docker_utils.py
pysimplesql/language_pack.py
pysimplesql/pysimplesql.py

New progress bar update adds a hide delay in milliisecs.  The progress bar will not display until after this delay is reached.  In fact, the progress bar Window is not even created until the delay is reached.  
Examples are very snappy now - the docker and sqlite ones especially, but even the slower HelioHost examples feel quite a bit better now too.

Progress bar hide delay

---

examples/SQLServer_examples/docker/Journal.sql
examples/SQLServer_examples/journal_sqlserver_docker.py
pysimplesql/pysimplesql.py

Added a new SQLDriver for Microsoft SQL Server.  Added an example that uses Docker to provide the server.  Needs some testing, but my quick tests went very well

Add MS SQLServer support

---

pysimplesql/pysimplesql.py

rel rename

---

examples/MSAccess_examples/journal_msaccess.py

This works on my system.
progress bar creates issues.. trying to figure that one out

Add java_home to system environment

---

examples/MSAccess_examples/install_java.py
examples/MSAccess_examples/journal_msaccess.py
pysimplesql/pysimplesql.py

Changed from using threading to using multiprocessing - no more need to worry about the GUI/threading complications
Also separated the Java install stuff from the MS Access example so it can easily be used in other examples, or by users in their own projects

New ProgressAnimation class

---

pysimplesql/pysimplesql.py

DROP TABLE IF EXISTS now works.  Cleaned up the duplicate_record method quite a bit.  Added support for asymetrical quoting - I.e. quoting a table like [Journal], which is the proper MS Access method.

MS Access improvements

---

examples/MSAccess_examples/install_java.py
pysimplesql/pysimplesql.py

Test this out when you get a chance.  I think it shows some pretty good promise.  No need to merge until we've discussed things over.  I spent the whole last day learning asyncio, so I'm sure there is room for improvement in how I pulled this together.
This new version works a bit differently.  In hindsight, the threading version could probably work similarly, especially with Window.write_event_value.  
ProgressAnimate.run() wraps whatever function needs the animated progress - it then closes automatically when the process is finished.  The close() mehtod doesn't really do anything currently.
So I guess we now have 3 options:
- Threading (would need a slight rewrite) - would work similarly, but with the threading complications of the GUI and main thread stuff
- Multiprocessing - works, …

New ProgressAnimate class

---

pysimplesql/pysimplesql.py

this is probably more like you wanted

fix progressanimate trailing comments in _animate

---

examples/SQLite_examples/journal_internal.py
pysimplesql/pysimplesql.py

Thanks for your approval :)
I still have some open items to make LiveUpdate a bit more robust, but those are minor changes/additions, not more refactoring.

CellEdit / LiveUpdate / refactoring / row_backup convention

---

examples/SQLite_examples/journal_internal.py
pysimplesql/pysimplesql.py

Do you like this? Marking both unsaved (along with virtual)
https://user-images.githubusercontent.com/57631333/236514752-213d510c-a4d4-47cc-ad1f-a56843efc813.mp4

Use Marker for Unsaved sg.Table Row / Big Performance Improvements / Change attrs["virtual"] to be a list of pks

---

pysimplesql/pysimplesql.py

Before:
https://github.com/PySimpleSQL/pysimplesql/assets/57631333/f868ff3d-3259-42d4-97f8-2fb631455559
After:
https://github.com/PySimpleSQL/pysimplesql/assets/57631333/7e87609e-8095-4f22-9b15-405adf923fa9

Feat update search to cycle through all found pks
